### ISSUE TITLE
Plugin does not inline resources

### ISSUE THREAD

**Issue by alekpentchev** [shff/parcel-plugin-inliner#1]
Hello!

I've tried to use your plugin but unfortunately it does not inline all css and js resources. I've installed the plugin and then typed "parcel build index.html". It produced normal set of parcel files instead of one html. What's more, even the html file consisted of only html, not both html, css and js.

I use node 8.11.3, npm 6.2.0.

**Comment by danielo515** [comment]
I have exactly the same problem

**Comment by danielo515** [comment]
I think the problem is related to this line:

```
process.env.NODE_ENV !== "production"
```
So it only unlined resources in production. 
It will be nice if it can check another additional env variable so you don't need to set env to production while developing. 

Something like 

```
process.env.NODE_ENV !== "production" || process.env.INLINE !== "yes"
```

**Comment by shff** [comment]
Hey guys!

Sorry I took that long to reply.

@danielo515 I believe that something along those lines will work. I'll work on it!

**Comment by shff** [comment]
Hello, sorry for the delay... I just added the `INLINE_ASSETS` option to force asset inlining and published that to NPM in the 1.0.2 version.

You can pass any value to that variable. E.g.:

```
# Will inline
INLINE_ASSETS=true NODE_ENV=development yarn build

# Won't inline
NODE_ENV=development yarn build
```

Hope that's what you guys need!

(Feel free to reopen if you have suggestions)

**Comment by swashcap** [comment]
Still seeing this behavior, even with `INLINE_ASSETS=true`. 😕

_Update:_ I'm using `--public-url` to publish to GH pages, so it can't be `.` as desired by this plugin.

**Comment by shff** [comment]
> Update: I'm using --public-url to publish to GH pages, so it can't be . as desired by this plugin.

Unfortunately the usage of `--public-url` is necessary, due to limitations in the dependencies I'm using. Using an absolute path throws the PostHTML plugin off.

Perhaps you could try running Parcel using `--public-url .` and then moving the files to the desired location?
