### ISSUE TITLE
Unable to configure the posthtml-inline-assets module

### ISSUE THREAD

**Issue by davideperozzi** [shff/parcel-plugin-inliner#10]
Hi!

There is currently no way to add custom transformations for the posthtml-inline-assets module.
As you wrote in the readme: "There are no configuration options".  
I don't know if this is a function that will come in the future, or if you didn't want to make it configurable at all. 
Either way, it would be great if the module was configurable for the poshtml plugin! :)

**Comment by davideperozzi** [comment]
Maybe this could also fix /issues/8, since you are able to pass custom transforms through your config file?

The configuration could be done this way: 

1. Create `posthtml.config.js` or `posthtmlrc` in your root directory.
2. Configure it: 
```js
// posthtml.config.js
module.exports = {
  plugins: {
    'posthtml-inline-assets': {
      transforms: {
        image: false,
      },
    },
  }
};
```

**Comment by shff** [comment]
This is interesting! I'll take a look into it later today! :D

**Comment by beaumartinez** [comment]
Ran into this myself.

I think you can simply `require` [posthtml-load-config](https://github.com/posthtml/posthtml-load-config) in order to allow this @shff.

**Comment by AndyOGo** [comment]
@shff 
May this be re-opened please?
