### ISSUE TITLE
Example links in README are broken.

### ISSUE THREAD

**Issue by kevincox** [shff/parcel-plugin-inliner#15]
Both of these links 404 for me.

> - Using link tags: https://gist.github.com/shff/8bf4606ecf1e3ee3ccee2a568d704c52
> - Using import in JS: https://gist.github.com/shff/cdcaa31275c8ba9a8e2e230f445654a3

**Comment by glennzw** [comment]
Anyone figured out how to do this? Looking for a simple CLI command to go from https://foo.com to a local foo.html file

**Comment by shff** [comment]
@glennzw This kind of thing is unrelated to this plugin. This is a Parcel plugin, not a command line tool. Look into the `inliner` npm package, it might help you there.

**Comment by shff** [comment]
@kevincox I removed the examples since they were outdated and redundant.

Feel free to open another issue if you need more examples than the ones in the README.
