### ISSUE TITLE
Comments are removed, overriding .terserrc file

### ISSUE THREAD

**Issue by alecgregory** [shff/parcel-plugin-inliner#18]
I would like to retain comments in my index.js file. I do this using a .terserrc file:
`{
  "output": {
    "comments": true
  }
}`

However, when using the plugin the comments are stripped from the inline file. Is there a way to preserve them?

**Comment by shff** [comment]
There is currently no way to preserve comments.

This kind of thing must be handled by the dependency [posthtml-inline-assets](https://github.com/jonathantneal/posthtml-inline-assets).

This plugin is merely a convenience wrapper, it doesn't perform the inlining itself.
