### ISSUE TITLE
Does this plugin support parcel version >= 2.0.0-beta.1?

### ISSUE THREAD

**Issue by TimDaub** [shff/parcel-plugin-inliner#20]
- Does this plugin support parcel version >= 2.0.0-beta.1?
- If it doesn't: What would need to change so it does?

Are PRs welcome?

**Comment by shff** [comment]
@TimDaub Unfortunately not. The name of this package is not compatible, and will never be compatible with Parcel v2 (unless we rename it!)... so we don't have a choice other than keep it as a V1 plugin.

Both versions of Parcel require plugins to have extremely specific names. For V1 it is `parcel-plugin-pluginName`, for V2 it is `parcel-pluginType-pluginName`.

Also the API is completely different, so it would need a rewrite from scratch anyway!

**Comment by TimDaub** [comment]
Thanks for letting me know and OK, too bad!
Maybe one day I find time to write one for V2...

**Comment by StanAngeloff** [comment]
This may help [Inline script and style tags :: v2.parceljs.org](https://v2.parceljs.org/languages/html/#inline-script-and-style-tags).

**Comment by shff** [comment]
@StanAngeloff Amazing, I'll add this link to the README file

Thank you :)
