### ISSUE TITLE
Unable to resolve local CSS files

### ISSUE THREAD

**Issue by alexlafroscia** [shff/parcel-plugin-inliner#3]
I had an `index.html` that references an adjacent `index.css` file. `inliner` was unable to resolve the CSS file; it just couldn't find it.

I think this stems from the need for this feature:

https://github.com/remy/inliner/issues/171

Since the Parcel plugin is unable to thread the correct location to resolve those relative references from on the file system through to Inliner.

For reference, the log from Inliner looks something like this:

```
  inliner html: 1 +0ms
  inliner inlining file +1ms
  inliner inliner.get file: /Users/alafroscia/Code/netflix/launcher-page-html/dist/index.html +1ms
  inliner processing HTML +1ms
  inliner { images: true,
  inliner   compressCSS: true,
  inliner   compressJS: true,
  inliner   collapseWhitespace: true,
  inliner   nosvg: false,
  inliner   skipAbsoluteUrls: false,
  inliner   preserveComments: false,
  inliner   iesafe: false } +0ms
  inliner loaded DOM +5ms
  inliner links: 1 +4ms
  inliner start 1 links +0ms
  inliner inliner.get file: /src.b1a1520c.css +0ms
  inliner skipping videos +0ms
  inliner ENOENT: src.b1a1520c.css, trying decodeURI +2ms
  inliner adding 0 CSS assets +2ms
  inliner images: 0 +0ms
  inliner collapsing whitespace +2ms
  inliner completed: 432 bytes +1ms
```

so it seems like it identifies the CSS file to resolve, but just fails to do so.

**Comment by shff** [comment]
Hi, @alexlafroscia !

As with the other issue I just closed, I believe the problem stems from having to run Parcel with `--public-url .` for it to work!

Here are some examples I made using `<link>` tags and using `import` in JS files:

https://gist.github.com/shff/8bf4606ecf1e3ee3ccee2a568d704c52
https://gist.github.com/shff/cdcaa31275c8ba9a8e2e230f445654a3

I'll add the info about `--public-url .` to the README

Let me know if this doesn't work for you! Feel free to reopen this issue if that's the case!

**Comment by ir-fuel** [comment]
@shff those github links give a 404
