### ISSUE TITLE
Cannot read property 'type' of null

### ISSUE THREAD

**Issue by omichelsen** [shff/parcel-plugin-inliner#4]
I'm getting this error when trying to run it:

```
Cannot read property 'type' of null
    at Bundler.bundler.on (/home/ole/projects/dilbert/node_modules/parcel-plugin-inliner/index.js:6:69)
    at Bundler.emit (events.js:182:13)
    at Bundler.bundle (/home/ole/projects/dilbert/node_modules/parcel-bundler/src/Bundler.js:324:12)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

I have a pretty simple setup with one `.less` file and one `.js` file referenced in `index.html`. I remembered to add `public-url` as well.

**Comment by shff** [comment]
Hmmm... I wonder if that's because of some internal change in Parcel itself.

Thanks for reporting, I will look into it ASAP.

**Comment by omichelsen** [comment]
Clarification: this happens if you do `parcel build src/*.html` rather than only having a single entry like `parcel build src/index.html`. The output from Parcel looks different in that case.

**Comment by shff** [comment]
@omichelsen Oooops, I had no idea I could have multiple entry points in Parcel 😄 

I adjusted the code so it works now. The commit is c34089d.

Also published to NPM. Sorry it took that long! :(

**Comment by shff** [comment]
And thanks for reporting!!

**Comment by omichelsen** [comment]
Thanks for the quick fix! 👍
